### ISSUE TITLE
Integrating with Server Side (IE - Laravel)

### ISSUE THREAD

**Issue by Failcookie** [creativetimofficial/ct-vue-paper-dashboard-pro#14]
This is really my first time integrating a SPA Vue setup with Laravel (just used Vue largely in one-offs, or something that was already initiated). Does anyone have any tips on getting started with the Dashboard in integrating with Laravel? I was hoping that running `yarn run build` and copying over the `index.html` to the `app.blade.php` file I have would work - but not quite there.

**Comment by cristijora** [comment]
Hi @Failcookie Thanks for using the dashboard! 
Unfortunately, I don't have experience with Laravel so I could give you a good solution that will work.
I will paste the content of an email to the same question. As far as it comes to integrate a SPA in Laravel, I am not sure if you want to do that if you have a SPA all the way because it's easier to keep them as separate projects. If you still want it integrated and have the same url for the api and your SPA then probably the message bellow will at least give you some hints to understand how to do it.

Unfortunately I am not very familiar with Laravel and would've loved to give you very precise instructions on how to integrate everything.
I do have experience with .NET MVC however which has pretty much the same idea behind. I have an article for that
https://medium.com/corebuild-software/vue-js-and-net-mvc-b5cede228626

You can give it a quick read so you could understand the idea and the setup. I know there is laravel-mix which is kind of a wrapper over webpack but not very sure how it works.
So, what you need in order to port this project to laravel are the following things:
  - Support .vue files (usually done through vue-loader)
  - Support ES6 (usually configured through babel-loader)
  - Sass support (sass-loader and node-sass)

As far as I know, laravel supports by default Vue and most of this stuff so just cross check the things above are supported in your configuration
After that, you could copy the `src` folder with the source code and `static` folder with static assets.
After you've done that make sure that in your html/blade files you also reference 
- Bootstrap
- Font-awesome
- Themify icons
- Montserat and Muli fonts
You can find these inside index.html from the dashboard.

**Comment by Failcookie** [comment]
Perfect! This will give me a good starting place. As I start the integration, I'll leave some notes on what I did to help others. This is a completely fresh project, so I should be able to help a few people. Report back soon!

**Comment by cristijora** [comment]
If the laravel specific webpack builder support vue-components (I think it does) then no, you don't have to follow up my webpack config. You can look at it just to get an idea of what happens.

**Comment by Failcookie** [comment]
Working my way through it now :) I am having to change a few file references to accommodate the Laravel file structure. 

@cristijora - Were you using a package to set pile paths for some files like `import Loading from 'src/components/Dashboard/Layout/LoadingMainPanel.vue'`? I am having to go through and change them to something like `'../../../../components/Dashboard/Layout/LoadingMainPanel.vue'`

**Comment by cristijora** [comment]
Hey @Failcookie do you have a webpack config or something like that ?

**Comment by cristijora** [comment]
I think you need something like this
```js
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}
mix.webpackConfig({
    resolve: {
        alias: {
           'src': resolve('src'),
       }
    }
});
```
`resolve('src')` might be slightly different depending on your folder structure

**Comment by Failcookie** [comment]
This is awesome! I didn't know that was a thing.. Webpack is so fascinating. Alright, I will swap that out today and test it out. I couldn't get it to work as intended right off the bat, so I probably just need to play around with the `resolve()` and get it where it needs to be. I'll report back soon..

**Comment by cristijora** [comment]
Thanks a lot @Failcookie for being so responsive. If we get to a good solution it will be valuable knowledge both for us, for you and for other people who want to integrate with Laravel. I would be very grateful if you can maybe put the setup on github so I can contribute with what I can in order to have a solid reference for other people and why not for yourself on other projects.

**Comment by Failcookie** [comment]
Absolutely! Once I have it all working as intended, I'll paste my `webpack.mix.js`, `package.json`, and note of any organization changes that I made outside of a fresh installation.  The next fun step will be handling the routing.. but I don't think that will be too terrible since I found some solid resources out there to use for reference, specifically starting here: https://mattstauffer.co/blog/getting-started-using-vues-vue-router-for-single-page-apps/

**Comment by Failcookie** [comment]
One step at a time so far! Everything compiled and we are loading up perfectly. Here are the gists of my code out of the gate with a fresh Laravel install.

https://gist.github.com/Failcookie/f85276736065a67b1ff2af1f2e764434

**Comment by j574144** [comment]
Hi all.

I have integrate it with  Laravel, you can see it here: https://github.com/j574144/Laravel-VLBD

 @cristijora  great work

**Comment by cristijora** [comment]
Update here. With V2, you can simply use https://github.com/yyx990803/laravel-vue-cli-3
copy paste the dashboard inside `frontend` and then add these options on top https://github.com/yyx990803/laravel-vue-cli-3/blob/master/frontend/vue.config.js of the dashboard's `vue.config.js` 
Should take 5-10mins to do that ❤️

**Comment by cristijora** [comment]
Closing this. Will add a small section in docs for laravel integration
