### ISSUE TITLE
Flags img in @2x 

### ISSUE THREAD

**Issue by mlumbroso** [creativetimofficial/ct-vue-paper-dashboard-pro#39]
Hello,

In the static/img/flags folder, images are currently 23x17, possible to have them in 46px width ?

Also noticed a few flags are missing : 
_ New Zealand
_ Malaysia
_ Albania
_ Cambodia
_ Cuba
_ Greece
_ Iceland

Any chance you add them ?

Thanks :)

**Comment by cristijora** [comment]
Hi @mlumbroso Will make sure that we add the missing flags in the next update.

**Comment by cristijora** [comment]
@mlumbroso I didn't include flags because you can easily find even svgs online on github for example https://github.com/hjnilsson/country-flags/tree/master/svg
or https://github.com/lipis/flag-icon-css/tree/master/flags/4x3

I'd recommend using those svg rather than having a lot of `@2x, @3x` options. I'm even thinking of removing the flags images from the project in favor of `svgs`
