### ISSUE TITLE
call method from swal

### ISSUE THREAD

**Issue by xhijack** [creativetimofficial/ct-vue-paper-dashboard-pro#47]
hi,

```
handleDelete(index, row) {
        swal({
          title: '',
          text: 'Apakah anda yakin?',
          type: 'warning',
          showCancelButton: true,
          confirmButtonClass: 'btn btn-success btn-fill',
          cancelButtonClass: 'btn btn-danger btn-fill',
          confirmButtonText: 'Yes, delete it!',
          buttonsStyling: false
        }).then(function () {
          let service = communityService.delete(row.id);
          service.then(response => {
            if (response.status == 204) {
              swal({
                title: 'Deleted!',
                text: 'Komunitas berhasil dihapus',
                type: 'success',
                confirmButtonClass: 'btn btn-success btn-fill',
                buttonsStyling: false
              });
            }
          });
          this.getCommunities();
        });
```
I tried to implement swal. when I click ok. It must be deleted and then I call api for getting list. But this.getCommunities() not recognized. How to access outside method from swal?

**Comment by cristijora** [comment]
Hi @xhijack 

My first assumption here is that `this` is not the right context in this case.
You have a `.then(function () {` 
Anonymous functions usually have their own `this` while arrow functions `() =>` keep the context of the parent and this is why `this.getCommunities()` is not recognized because it tries to find it within `function()`

Simply change `then(function () {` to `then(() => {` and it should be fine

**Comment by xhijack** [comment]
you're awesome
 thanks @cristijora
