### ISSUE TITLE
Updating chart data

### ISSUE THREAD

**Issue by Fatflo** [creativetimofficial/ct-vue-paper-dashboard-pro#49]
Hello,
when I modify the data in this.activityChart.data (axis request inmounted event) on the Overview page, the chart is not updated.
Is there a way to trigger chart update ?

Thanks,
Florian

**Comment by cristijora** [comment]
Hello @Fatflo The charts are not reactive by default but you can change that quite easily. 
You can go to the `ChartCard` component and add a chart property to `data`
```
data() {
 return {
   chartId: 'no-id',
   $Chartist: null,
   chart: null
 }
}
```

Then save the initialized chart like this:

```js
this.chart = this.$Chartist[this.chartType](chartIdQuery, this.chartData, this.chartOptions)
```

After that, you could simply add a `watcher` on  `chartData` and update the chart reference. Chartist has an [update method](http://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update) 

```js
watch: {
 chartData(newData) {
  this.chart.update(newData)
 }
}
```

**Comment by cristijora** [comment]
Hey @Fatflo sorry for the really late response on this one.
Most likely `watch` is not triggered because it's not watched with `deep` property. Since in your case, chart data contains both `labels` and `series` what happens is that, only `series` is updated and the watcher doesn't recognize this as un update because it's a nested array that changed. 

Try this instead:

```js
chartData: {
 deep: true,
 handler(newValue){
  this.chart.update(newData)
 }
}
```

Also there is a [Version 2](https://www.creative-tim.com/product/vue-paper-dashboard-2-pro) of the dashboard which users Vue Chart.js and has reactivity option by default. If you don't have access to V2, let me know your username from creativetim and I will give you access to it.
