### ISSUE TITLE
How to integrate with vue.js project?

### ISSUE THREAD

**Issue by inoyatov** [creativetimofficial/ct-vue-paper-dashboard-pro#57]
I bought  Vue PaperKit Pro 2 but there is no information how to integrate with project. Can you provide briefly how it can be integrated with project . (I am using following template for my project https://github.com/cretueusebiu/laravel-vue-spa)

**Comment by cristijora** [comment]
Hello @inoyatov 
Thanks for using our products first of all.

Unfortunately we don't have out of the box support for laravel yet. The dashboard is based on Vue CLI 3 and is built as a SPA (single page app). 
For integrating it with laravel I can recommend this repo https://github.com/yyx990803/laravel-vue-cli-3/tree/master/frontend since it's created by the author of Vue.js 
 What you can do with this template, is simply copy pase the Vue Paper Dashboard PRO folder inside `frontend` folder, install dependencies then add these options in `vue.config.js` 
https://github.com/yyx990803/laravel-vue-cli-3/blob/master/frontend/vue.config.js

This should make everything work and you will have the dashboard inside the `frontend` folder.
