### ISSUE TITLE
weird style on select

### ISSUE THREAD

**Issue by mr-chick** [creativetimofficial/ct-vue-paper-dashboard-pro#65]
Hey,

Any ideea why the select box looks like that?
It has a readonly tag on it, and the arrow has a background bigger than the input (when it animates, it's corners exit the input boundry)

![screenshot_20180831_114705](https://user-images.githubusercontent.com/8880757/44903146-6f1e2d80-ad14-11e8-9198-e6f5bba0eee6.png)

**Comment by cristijora** [comment]
Hi @mr-chick I am doing an update on this dashboard right now. Unfortunately the issue you described and the screenshot belongs to another theme. https://github.com/creativetimofficial/ct-vue-light-bootstrap-dashboard-pro If it's still relevant to you, please open an issue there and it will be fixed in the next update.
