### ISSUE TITLE
Vue Paper Dashboard 2 Free some code still uses Bootstrap 3

### ISSUE THREAD

**Issue by nmfzone** [creativetimofficial/ct-vue-paper-dashboard-pro#70]
Okay, so let me explain some of my experience using `Paper Dashboard 2` free version.

Like what I've said, I found some code from Paper Dashboard 2 Free version that still uses Bootstrap 3.

There is example from what i've found:

```
.has-error {
  .form-control-feedback, .control-label {
    color: $danger-color;
  }
}

.has-success {
  .form-control-feedback, .control-label {
    color: $success-color;
  }
}
```

The Bootstrap 4 uses different input error & success handling. So, correct me if I'm wrong. Thanks

Fyi, I'm `nmfdev` who comment [here](https://www.creative-tim.com/product/vue-paper-dashboard-2-pro).

> Hey, I just want to ask for clarification. If we buy the pro version of this template, can we get all css code in Bootstrap 4 version? Because last time I downloaded the free version of this template (Paper Dashboard 2), there are lots of css code that still using Bootstrap 3. Thanks

**Comment by nmfzone** [comment]
@cristijora Any though on this?

**Comment by cristijora** [comment]
@nmfzone thanks a lot for the suggestions.
We did an update to the template and cleaned up some scss code and upgraded to latest version of bootstrap as well. Regarding the class names, I am aware that they are a bit different from bootstrap ones (`is-invalid`, `is-valid`) but we had to use them because of various states of the inputs (inputs with addons on the left and right) and we consider the addons (e.g. icons) as part of the input and we need to highlight the whole input when it has an error vs highlighting only a part of it like in the original bootstrap. Hope this makes sense to you. If you still have any issues, feel free to re-open this ssue
