### ISSUE TITLE
required prop in fg-input is not working on login page

### ISSUE THREAD

**Issue by sulmanweb** [creativetimofficial/ct-vue-paper-dashboard-pro#73]
```html
<fg-input
                  v-model="form.auth"
                  addon-left-icon="nc-icon nc-single-02"
                  placeholder="Email"
                  :required="true"
                  type="email"
                ></fg-input>
```
results in
```html
<input aria-describedby="addon-right addon-left" placeholder="Email" type="email" class="form-control">
```

**Comment by cristijora** [comment]
@sulmanweb this issue has been fixed in the latest update (2.2.0) 
The `fg-input` should now handle required attribute properly. To upgrade, just download the dashboard archive again from creative tim and follow [migration instructions](https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation/migration-guide.html#from-2-1-0-to-2-2-0)
